rm -r src/utils/__pycache__/
rm -r src/__pycache__/
rm -r src/release_GP/__pycache__/
rm -r __pycache__
rm -r tests/CA/*
rm -r tests/certificates/*
rm -r tests/keys/*
rm -r tests/randomness/*
rm -r tests/hash/*
rm -r Alice
rm -r Bob
rm -r Bingo
rm -r Blockchain
rm -r MdI
rm -r AS/